[package]
name = "rendy_playground"
version = "0.1.0"
authors = ["sim82 <simberger@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
vulkan = []
x11 = []
spirv-reflection = []

[dependencies]
rendy = { version ="0.4", features = ["vulkan"]}
rendy-texture = { version="0.4", features = ["image"]}
failure = "0.1"
gfx-backend-vulkan = {version = "0.3", features = ["x11"]}
# gfx-hal = {version = "0.3"}
lazy_static = "*"
log = "*"
env_logger = "*"
#failure = "*"
rendy-wsi = "0.4"
rendy-shader = "0.4"
rand = "0.6"
palette = "*"
genmesh = "*"
nalgebra = "*"
# nalgebra-glm = "*"
image = "*"
winit = "*"
num-traits = "*"
clap = "*"
rayon = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
ndarray = "*"
packed_simd = "*"
itertools = "*"
bincode = "*"
random_color = "*"
